### ISSUE TITLE
Unable to customize text colors for x-axis and y-axis

### ISSUE THREAD

**Issue by EzekielWachira** [carlosgub/kotlinm-charts#1]
I'm unable to customize the text colors for both x-axis and y-axis. Text appears black on dark mode so It's impossible to see the values

**Comment by carlosgub** [comment]
Hi @EzekielWachira give me this week to make this possible :D, Also I will update the compose library to 1.5.1

**Comment by carlosgub** [comment]
I do an example with the current code, you need to pass xAxisLabel and a yAxisLabel Composables in the constructor as you see in my image, I changed in that way the color of the text to blue.
<img width="1272" alt="Screenshot 2023-09-17 at 7 41 15 PM" src="https://github.com/carlosgub/kotlinm-charts/assets/30916886/fe49063e-c3e4-4a30-8291-c2bdb5c59211">

**Comment by EzekielWachira** [comment]
It worked thank you.
