### ISSUE TITLE
Failed to resolve: com.carlosgub.kotlinm.charts:charts:1.0.4

### ISSUE THREAD

**Issue by EzekielWachira** [carlosgub/kotlinm-charts#5]
Cannot download latest version.

getting:

`Failed to resolve: com.carlosgub.kotlinm.charts:charts:1.0.4`

I'm using gradle version catalog

**Comment by carlosgub** [comment]
it's strange https://github.com/carlosgub/kotlinm-charts/packages/1933121 here is published, can you try again :( , I used this version in my personal app and work well :(

**Comment by EzekielWachira** [comment]
I'me getting the same message:

`Failed to resolve: com.carlosgub.kotlinm.charts:charts:1.0.4`

**Comment by EzekielWachira** [comment]
Version 1.0.3 had the same issue

**Comment by EzekielWachira** [comment]
I have added the required credentials but I'm only able to download `v1.0.2` but unable to download both `1.0.3` and `1.0.4`

**Comment by EzekielWachira** [comment]
<img width="1512" alt="Screenshot 2023-09-21 at 13 15 56" src="https://github.com/carlosgub/kotlinm-charts/assets/48563395/4a7231d9-9d6a-4531-8565-da7167a097d2">

**Comment by carlosgub** [comment]
Hi, I already deleted .m2 from the root of my computer, clean the cache of android studio only if some cache is giving me the 1.0.4 to my project but its running perfectly. Can you try of invalidate your cache in android studio ?
<img width="427" alt="image" src="https://github.com/carlosgub/kotlinm-charts/assets/30916886/161c3927-aa82-4819-896d-541e10409d33">

**Comment by EzekielWachira** [comment]
I tried that but it's not working

**Comment by EzekielWachira** [comment]
<img width="1512" alt="Screenshot 2023-09-21 at 21 20 48" src="https://github.com/carlosgub/kotlinm-charts/assets/48563395/7c8a60e2-c757-4bf0-8ff9-2f486f7f1717">

**Comment by EzekielWachira** [comment]
Same problem with `1.0.3`

<img width="1512" alt="Screenshot 2023-09-21 at 21 25 02" src="https://github.com/carlosgub/kotlinm-charts/assets/48563395/2ead9605-ec46-488e-b8b1-04abd7643558">

**Comment by carlosgub** [comment]
Hi, try to create a new github token and try again plis. Really I don't know why this is happening :(  https://stackoverflow.com/questions/58987363/gradle-fails-to-download-package-from-github-package-registry

```
maven {
    name = "GitHubPackages"
    url = uri("https://maven.pkg.github.com/carlosgub/kotlinm-charts")
    
    credentials {
        username = <YOUR_GITHUB_USERNAME>
        password =  **NEW_TOKEN_HERE**
    }
}
```

**Comment by EzekielWachira** [comment]
Finally it worked thank's for your support
